version: 2
jobs:
  build:
    docker:
      - image: bermeitingerb/texlive:latest
    steps:
      - checkout
      - run: 
          name: Build with LatexMK
          command: |
            mkdir /output;
            latexmk;
            cp main.pdf /output/;
            latexmk -C
            zip -r --exclude='*.git*' --exclude='*.circleci*' --exclude='latexmkrc' /output/arxiv.zip .;
      - store_artifacts:
          path: /output
