version: 2.0

jobs:
  "latest":
    docker:
      - image: bermeitingerb/texlive:latest
    steps:
      - checkout
      - run:
          name: Build with LatexMK
          command: latexmk
      - run:
          name: Rename artifact
          command: mv main.pdf main-latest.pdf
      - store_artifacts:
          path: main-latest.pdf
 
  "arxiv":
    docker:
      - image: bermeitingerb/texlive:2016
    steps:
      - checkout
      - run:
          name: Build with LatexMK
          command: latexmk
      - run:
          name: Rename artifact
          command: mv main.pdf main-arxiv.pdf
      - store_artifacts:
          path: main-arxiv.pdf
      - run:
          name: Clean unneeded files
          command: latexmk -C
      - run:
          name: Zip files
          command: zip -r --exclude='*.git*' --exclude='*.circleci*' --exclude='latexmkrc' --exclude='README.md' arxiv.zip .
      - store_artifacts:
          path: arxiv.zip

workflows:
  version: 2
  build:
    jobs:
      - "latest"
      - "arxiv"
